//PRODUCTION KEYS
module.exports={
  GOOGLECLIENTID:process.env.GOOGLE_CLIENT_ID,
  GOOGLECLIENTSECRET:process.env.GOOGLE_CLIENT_SECRET,
  MONGOURI:process.env.MONGO_URI,
  COOKIEKEY:process.env.COOKIE_KEY
}
