//PRODUCTION KEYS
module.exports = {
  GOOGLECLIENTID: process.env.GOOGLE_CLIENT_ID,
  GOOGLECLIENTSECRET: process.env.GOOGLE_CLIENT_SECRET,
  MONGOURI: process.env.MONGO_URI,
  COOKIEKEY: process.env.COOKIE_KEY,
  STRIPEPUBLISHABLEKEY: process.env.STRIPEPUBLISHABLEKEY,
  STRIPESECRETKEY: process.env.STRIPESECRETKEY,
  SEND_GRID_API_KEY: process.env.SEND_GRID_API_KEY,
  REDIRECT_DOMAIN: process.env.REDIRECT_DOMAIN
};
